services:
  db:
    networks:
      - court-network

    image: pgvector/pgvector:pg16
    container_name: court_db

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "court_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root_password"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  kafka:
    networks:
      - court-network

    image: apache/kafka:3.7.0
    container_name: court-kafka-broker
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:29093,BROKER://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    networks:
      - court-network

    image: provectuslabs/kafka-ui:latest
    container_name: court-kafka-ui
    depends_on:
      - kafka
    ports:
      - "7777:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_MODE: "true"
      AUTH_TYPE: disabled
    restart: unless-stopped

  ollama:
    networks:
      - court-network

    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

  app:
    networks:
      - court-network

    build: .
    container_name: j-court
    depends_on:
      - db
      - kafka
      - kafka-ui
      - ollama
    ports:
      - "7070:7070"
    environment:

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/court_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password

      NOTIFICATION_LOGIN: ${NOTIFICATION_LOGIN}
      NOTIFICATION_PASSWORD: ${NOTIFICATION_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}

      SHOW_SQL: true

      JAVA_OPTS: "-Xms256m -Xmx512m"

    restart: unless-stopped

volumes:
  postgres_data: { }
  ollama_data: { }


networks:
  court-network:
    driver: bridge